//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektRaport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Changes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Changes()
        {
            this.Report = new HashSet<Report>();
        }
    
        public int ID { get; set; }
        public int FristWorker { get; set; }
        public Nullable<int> SecondWorker { get; set; }
        public string TimeRange { get; set; }

        public System.DateTime Date { get; set; }
    
        public virtual Workers Workers { get; set; }
        public virtual Workers Workers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
    }
}
