//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektRaport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public int ChangeID { get; set; }
        public string IncidentNumber { get; set; }
        public string ContentIncident { get; set; }
        public string ActionToken { get; set; }
        public string DeviceNumber { get; set; }
        public string DeviceName { get; set; }
        public int ActionTime { get; set; }
    
        public virtual Changes Changes { get; set; }
    }
}
